Hardhatify Poll, PollCreator, VariableSupplyToken tests👷
livepeer/protocol pull request #426
Opened 2021-07-26 17:12 UTC by kyriediculous

**What does this pull request do? Explain your changes. (required)**
Hardhatify Poll, PollCreator, VariableSupplyToken tests 👷

2021-07-26 19:17 UTC, kautukkundan requested changes
Test failing for `VariableSupplyToken` due to unavailable signer

2021-07-26 19:17 UTC, kautukkundan commented on test/unit/VariableSupplyToken.js
> +        token = await (await ethers.getContractFactory("VariableSupplyToken")).new()
```suggestion
        token = await (await ethers.getContractFactory("VariableSupplyToken")).deploy()
```

2021-07-26 19:17 UTC, kautukkundan commented on test/unit/VariableSupplyToken.js
> +            await token.mint(accounts[0], 500)
```suggestion
            await token.mint(accounts[0].address, 500)
```

2021-07-26 19:17 UTC, kautukkundan commented on test/unit/VariableSupplyToken.js
should add an `accounts` variable to store `ethers.getSigners()`

2021-07-26 19:17 UTC, kautukkundan commented on test/unit/VariableSupplyToken.js
>              const balance = await token.balanceOf(accounts[0])
```suggestion
            const balance = await token.balanceOf(accounts[0].address)
```

2021-07-28 17:18 UTC, kyriediculous commented
should be fixed

2021-07-28 18:03 UTC, kautukkundan approved these changes

2021-07-28 18:49 UTC, merged